(function(window, document) {
  'use strict';

  window.ActionTypes = {
    GET_STATE: 'GET_STATE',
    SET_STATE: 'SET_STATE',

    CREATE_SITE: 'CREATE_SITE',
    SITE_CREATED: 'SITE_CREATED',
    UPDATE_SITE: 'UPDATE_SITE',
    SITE_UPDATED: 'SITE_UPDATED',
    DELETE_SITE: 'DELETE_SITE',
    SITE_DELETED: 'SITE_DELETED',
    ORDER_SITES: 'ORDER_SITES',
    SITES_ORDERED: 'SITES_ORDERED',

    UPDATE_SITE_SETTINGS: 'UPDATE_SITE_SETTINGS',
    SITE_SETTINGS_UPDATED: 'SITE_SETTINGS_UPDATED',
    SITE_SETTINGS_CREATED: 'SITE_SETTINGS_CREATED',
    DELETE_SITE_SETTINGS: 'DELETE_SITE_SETTINGS',
    SITE_SETTINGS_DELETED: 'SITE_SETTINGS_DELETED',
    RENAME_SITE_SETTINGS_SITENAME: 'RENAME_SITE_SETTINGS_SITENAME',

    UPDATE_SITE_TEMPLATE_SETTINGS: 'UPDATE_SITE_TEMPLATE_SETTINGS',
    SITE_TEMPLATE_SETTINGS_UPDATED: 'SITE_TEMPLATE_SETTINGS_UPDATED',
    SITE_TEMPLATE_SETTINGS_CREATED: 'SITE_TEMPLATE_SETTINGS_CREATED',
    DELETE_SITE_TEMPLATE_SETTINGS: 'DELETE_SITE_TEMPLATE_SETTINGS',
    SITE_TEMPLATE_SETTINGS_DELETED: 'SITE_TEMPLATE_SETTINGS_DELETED',
    RENAME_SITE_TEMPLATE_SETTINGS_SITENAME: 'RENAME_SITE_TEMPLATE_SETTINGS_SITENAME',

    CREATE_SITE_SECTION: 'CREATE_SITE_SECTION',
    SITE_SECTION_CREATED: 'SITE_SECTION_CREATED',
    UPDATE_SITE_SECTION: 'UPDATE_SITE_SECTION',
    SITE_SECTION_UPDATED: 'SITE_SECTION_UPDATED',
    RESET_SITE_SECTION: 'RESET_SITE_SECTION',
    DELETE_SITE_SECTION: 'DELETE_SITE_SECTION',
    SITE_SECTION_DELETED: 'SITE_SECTION_DELETED',
    ORDER_SITE_SECTIONS: 'ORDER_SITE_SECTIONS',
    SITE_SECTIONS_ORDERED: 'SITE_SECTIONS_ORDERED',
    RENAME_SITE_SECTIONS_SITENAME: 'RENAME_SITE_SECTIONS_SITENAME',
    DELETE_SITE_SECTIONS: 'DELETE_SITE_SECTIONS',
    SITE_SECTIONS_DELETED: 'SITE_SECTIONS_DELETED',

    SITE_SECTION_BACKGROUND_DELETE: 'SITE_SECTION_BACKGROUND_DELETE',
    SITE_SECTION_BACKGROUND_DELETED: 'SITE_SECTION_BACKGROUND_DELETED',
    SITE_SECTION_BACKGROUND_ORDER: 'SITE_SECTION_BACKGROUND_ORDER',
    SITE_SECTION_BACKGROUND_ORDERED: 'SITE_SECTION_BACKGROUND_ORDERED',

    ADD_SECTION_TAGS: 'ADD_SECTION_TAGS',
    UPDATE_SECTION_TAGS: 'UPDATE_SECTION_TAGS',
    RENAME_SECTION_TAGS: 'RENAME_SECTION_TAGS',
    RENAME_SECTION_TAGS_SITENAME: 'RENAME_SECTION_TAGS_SITENAME',
    DELETE_SECTION_TAGS: 'DELETE_SECTION_TAGS',
    SITE_SECTIONS_TAGS_DELETED: 'SITE_SECTIONS_TAGS_DELETED',
    ADD_SITE_SECTIONS_TAGS: 'ADD_SITE_SECTIONS_TAGS',
    DELETE_SITE_SECTIONS_TAGS: 'DELETE_SITE_SECTIONS_TAGS'
  };
})(window, document);
