(function (window) {
  'use strict';

  window.ActionTypes = {
    GET_STATE: 'GET_STATE',
    SET_STATE: 'SET_STATE',

    CREATE_SITE_SECTION: 'CREATE_SITE_SECTION',

    INIT_UPDATE_SITE_SETTINGS: 'INIT_UPDATE_SITE_SETTINGS',
    UPDATE_SITE_SETTINGS: 'UPDATE_SITE_SETTINGS',

    INIT_UPDATE_SITE_TEMPLATE_SETTINGS: 'INIT_UPDATE_SITE_TEMPLATE_SETTINGS',
    UPDATE_SITE_TEMPLATE_SETTINGS: 'UPDATE_SITE_TEMPLATE_SETTINGS',

    INIT_CREATE_SITE_SECTION: 'INIT_CREATE_SITE_SECTION',
    INIT_UPDATE_SITE_SECTION: 'INIT_UPDATE_SITE_SECTION',
    UPDATE_SITE_SECTION: 'UPDATE_SITE_SECTION',
    INIT_ORDER_SITE_SECTIONS: 'INIT_ORDER_SITE_SECTIONS',
    ORDER_SITE_SECTIONS: 'ORDER_SITE_SECTIONS',
    INIT_DELETE_SITE_SECTION: 'INIT_DELETE_SITE_SECTION',
    DELETE_SITE_SECTION: 'DELETE_SITE_SECTION',

    INIT_ORDER_SITE_SECTION_BACKGROUNDS: 'INIT_ORDER_SITE_SECTION_BACKGROUNDS',
    ORDER_SITE_SECTION_BACKGROUNDS: 'ORDER_SITE_SECTION_BACKGROUNDS',
    INIT_DELETE_SITE_SECTION_BACKGROUND: 'INIT_DELETE_SITE_SECTION_BACKGROUND',
    DELETE_SITE_SECTION_BACKGROUND: 'DELETE_SITE_SECTION_BACKGROUND',

    ADD_SECTION_TAGS: 'ADD_SECTION_TAGS',
    INIT_ORDER_SECTION_TAGS: 'INIT_ORDER_SECTION_TAGS',
    ORDER_SECTION_TAGS: 'ORDER_SECTION_TAGS',
    INIT_UPDATE_SECTION_TAGS: 'INIT_UPDATE_SECTION_TAGS',
    UPDATE_SECTION_TAGS: 'UPDATE_SECTION_TAGS',
    RENAME_SECTION_TAGS: 'RENAME_SECTION_TAGS',
    DELETE_SECTION_TAGS: 'DELETE_SECTION_TAGS',

    ADD_SECTION_ENTRIES: 'ADD_SECTION_ENTRIES',
    INIT_CREATE_SECTION_ENTRY: 'INIT_CREATE_SECTION_ENTRY',
    INIT_UPDATE_SECTION_ENTRY: 'INIT_UPDATE_SECTION_ENTRY',
    UPDATE_SECTION_ENTRY: 'UPDATE_SECTION_ENTRY',
    INIT_UPDATE_SECTION_ENTRIES: 'INIT_UPDATE_SECTION_ENTRIES',
    INIT_MOVE_ENTRY_TO_SECTION: 'INIT_MOVE_ENTRY_TO_SECTION',
    RENAME_SECTION_ENTRIES: 'RENAME_SECTION_ENTRIES',
    INIT_ORDER_SECTION_ENTRIES: 'INIT_ORDER_SECTION_ENTRIES',
    ORDER_SECTION_ENTRIES: 'ORDER_SECTION_ENTRIES',
    INIT_ORDER_SECTION_ENTRY_GALLERY: 'INIT_ORDER_SECTION_ENTRY_GALLERY',
    ORDER_SECTION_ENTRY_GALLERY: 'ORDER_SECTION_ENTRY_GALLERY',
    INIT_DELETE_ENTRY_GALLERY_IMAGE: 'INIT_DELETE_ENTRY_GALLERY_IMAGE',
    DELETE_ENTRY_GALLERY_IMAGE: 'DELETE_ENTRY_GALLERY_IMAGE',
    INIT_DELETE_SECTION_ENTRY: 'INIT_DELETE_SECTION_ENTRY',
    DELETE_SECTION_ENTRY: 'DELETE_SECTION_ENTRY',
    INIT_DELETE_SECTION_ENTRIES: 'INIT_DELETE_SECTION_ENTRIES',
    DELETE_SECTION_ENTRIES: 'DELETE_SECTION_ENTRIES'
  };
})(window);
